/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "intro",
    "getting-started",
    "Limitations",
    "best-practices",
    {
      type: 'category',
      label: 'APIs',
      items: [
        "apis/account-input",
        "apis/account-instructions",
        "apis/account-transaction",
        "apis/block",
        "apis/block-rewards",
        "apis/instruction",
        "apis/native-stake",
        "apis/native-vote",
        "apis/native-token",
        "apis/nativeBPF",
        "apis/serum",
        "apis/transaction",
        "apis/transaction-log",
        "apis/transaction-signature",
        "apis/step-finance"
      ]
    },
    {
      type: 'category',
      label: 'Models',
      items: [
        "models/account-input",
        "models/account-instruction",
        "models/account-transaction",
        "models/block",
        "models/block-reward",
        "models/epoch",
        "models/instruction",
        "models/token",
        "models/transaction",
        "models/transaction-log",
        "models/transaction-signature",
      ],
    },
    "dynamic-queries",
    "nested-queries"    // {
    //   type: 'autogenerated',
    //   dirName: '.'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
